name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.2.8'
          cabal-version: '3.8.1.0'

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test --test-show-details=direct
